version: 2.1
commands: 
  install-vault:
    steps:
      - run:
          name: Install Vault and prereqs
          command: |
            vault -h && exit 0 || echo "Installing vault"
            # only runs if vault command above fails
            cd /tmp
            wget https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip
            unzip vault_1.12.2_linux_amd64.zip
            sudo mv vault /usr/local/bin        
            vault -h
  vault-auto-auth:
    description: "Use Vault auto auth to load secrets"
    steps:
      - run:
          name: Auto-authenticate with Vault
          command: |
            # Write the CircleCI provided value to a file read by Vault
            echo $CIRCLE_OIDC_TOKEN > .circleci/vault/token.json
            # Substitute the env vars in our context to render the Vault config file
            sudo apt update && sudo apt install gettext-base
            envsubst < .circleci/vault/agent.hcl.tpl > .circleci/vault/agent.hcl
            echo "Hello world"
            # # This config indicates which secrets to collect and how to authenticate     
            # vault agent -config=.circleci/vault/agent.hcl
      - run:
          name: Set Environment Variables from Vault
          command: |
            # In order to properly expose values in Environment, we _source_ the shell values written by agent
            source .circleci/vault/setenv
jobs:
  setup-vault-and-load-secrets:
    machine: true
    resource_class: db-cci-ns/macos-runner
    steps:
      - add_ssh_keys:
          fingerprints:
            - "derry/.ssh/id_rsa_de:25:99:fe:85:f6:0a:ad:6f:f5:42:bf:3f:02:ee:28"
      - checkout
      - install-vault
      - vault-auto-auth
      - run: 
          name: Use secrets retrieved from Vault in a subsequent step
          command: |
            echo "Username is $SECRET_DEMO_USERNAME, password is $SECRET_DEMO_PASSWORD"
workflows:
  vault: 
    jobs:
      - setup-vault-and-load-secrets:
          context:
            - circleci-vault-demo
# VS Code Extension Version: 1.5.1

# version: 2.1
# workflows:
#   testing:
#     jobs:
#       - compute
#       - runner-test
# jobs:
#   runner-test:
#     machine: true
#     resource_class: db-cci-ns/macos-runner
#     steps:
#       - run: echo "Hi I'm on Runners!"
  
#   compute:
#     docker: 
#       - image: cimg/node:17.2.0
#     steps:
#       - run: echo "Hi I'm on Runners!"