version: 2.1

workflows:
  vault-workflow:
    jobs: 
      - vault-connection

jobs:
  vault-connection:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: "Hello World" 